-- =====================================================
-- 508_po_email_followup.sql — 508 적재 후 잔여 확인 (조회 전용, 데이터 변경 없음)
--
-- 2026-08-13 508 실행 결과: 원가표 112 / 별칭연결 93 / 미연결 17 / 적용확인 92.
--   A) 미연결 17건이 어떤 매입처인지
--   B) 원가표 이메일과 다른 값을 가진 거래처(기존값 보존분)
--
-- 508과 같은 이유로 각 쿼리는 자체 VALUES 목록을 갖는다 (Supabase 편집기는
-- 문장을 독립 실행하므로 보조 테이블 사용 불가).
-- =====================================================


-- ── A) 미연결 17건: 원가표에는 있으나 매입처 마스터와 안 이어진 곳 ──
-- 이 매입처들은 발주 시 이메일이 자동으로 채워지지 않는다.
WITH po_emails(vendor_name, email) AS (VALUES
  ('(주)다이아'::text, 'daiya1991@naver.com'::text),
  ('(주)소셜빈', 'kisung@socialbean.co.kr'),
  ('AtoZ', 'k398551@naver.com'),
  ('DMC미디어', 'kkw2954@dmcmedia.co.kr'),
  ('GB컴퍼니', 'gb-support@golfboom.com'),
  ('JW아이엔씨', '7013355@jwinc.shop'),
  ('JW컴퍼니', 'karismapark48@hanmail.net'),
  ('THE SG', 'thesg0_s@naver.com'),
  ('㈜다이아', 'daiya1991@naver.com'),
  ('㈜소셜빈', 'kisung@socialbean.co.kr'),
  ('㈜에벤에셀기업', 'ebes@ebes.co.kr'),
  ('골프맥스', 'golmac@naver.com'),
  ('괴산꿀벌랜드', 'golcan@hanmail.net'),
  ('구씨공방', 'jongseok1188@hanmail.net'),
  ('기프트넷', 'gift@giftnet.co.kr'),
  ('나래티앤씨', 'admin@naraetnc.com'),
  ('나비스토리', 'ahj0417@sknabi.com'),
  ('남양유업', 'clc0718@namyangi.com'),
  ('네오프라자', 'neoplaza@neoplaza.co.kr'),
  ('네이처프라임', 'sales@nprime.co.kr'),
  ('뉴샵', 'newshop2026@naver.com'),
  ('느티나무의사랑', 'huz@huz.co.kr'),
  ('다온글로비스', 'daonglovis@daum.net'),
  ('다올에프앤지', 'daolfng@gmail.com'),
  ('다올커머스', 'daol87456@hanmail.net'),
  ('다즐코리아', 'doskoi@naver.com'),
  ('대길', '9477848@naver.com'),
  ('대상크리스탈', 'leebo99@hanmail.net'),
  ('대왕크린', 'dwtissue@naver.com'),
  ('대현상회', 'dhoil1970@naver.com'),
  ('도기야', 'new@livingnara.com'),
  ('동양키친나라', 'kcnr@hanmail.net'),
  ('두일지엘', 'ub3@ubkorea.co.kr'),
  ('라인플러스', 'sales@lineplus.com'),
  ('락앤락', 'hyuckgyu.kwon@locknlock.com'),
  ('렌켄', 'moondaeho1@naver.com'),
  ('로얄오피스', 'royalinkr@hanmail.net'),
  ('롯데택배', 'yoaluv@naver.com'),
  ('루체컴퍼니', 'luce-co@naver.com'),
  ('루치펠로', 'bavscd@rucipello.com'),
  ('리버191', 'evergreenkch@hanmail.net'),
  ('리베로앤', 'liberon4992200@daum.net'),
  ('명성', 'zerodrom21@gift.co.kr'),
  ('모든컴퍼니', 'admin@moduen.com'),
  ('무아스', 'offline@mooas.com'),
  ('무한타올우정상사', 'woojungtowel@naver.com'),
  ('바르미식품', 'barmifd@naver.com'),
  ('반디상사', 'queen-made@naver.com'),
  ('베스트라인', 'bestlinee@naver.com'),
  ('벨라코리아', 'help@bellakorea.kr'),
  ('브랜즈컴퍼니', 'b2b@brandz.co.kr'),
  ('브로스앤컴퍼니', 'yjseo@brosncompany.com'),
  ('비앤디', 'bndsa001@bndkorea.com'),
  ('비오인터내셔널', 'bointl1@naver.com'),
  ('비즈모아코리아', 'bizmoakorea@naver.com'),
  ('비즈엠넷코리아', 'thinking@bizmnet.co.kr'),
  ('비타그램', 'vitagram001@naver.com'),
  ('샘빌', 'yoonki@semvill.com'),
  ('서우글로벌', 'seowoo.njy@gmail.com'),
  ('선명농수산', 'sm22@sunnuts.co.kr'),
  ('선학', 'mblco@naver.com'),
  ('성진코아', 'whyun@sungjincore.co.kr'),
  ('세정CCR', 'sejungccr@naver.com'),
  ('솔트바이오', 'sbhmudsalt@saltbio.com'),
  ('송월타올수건이야기', 'towel79@naver.com'),
  ('쉔코리아', 'schoenkorea1@schoenkorea.co.kr'),
  ('승일', 'thinking@bizmnet.co.kr'),
  ('시즈넬', 'tfsdiffuser@gmail.com'),
  ('신성트레이드', 'kyuil9191@hanmail.net'),
  ('신영인터내셔널', 'syglc@naver.com'),
  ('신영종합상사', 'sypen@naver.com'),
  ('실리만', 'pjh@sillymann.com'),
  ('씨엘피에스', 'hbk0609@hanmail.net'),
  ('아로마코에스', 'ceo01@aromacos.kr'),
  ('아이랩코퍼레이션', 'order@ilabcorp.co.kr'),
  ('아이템허브', 'itemhub-laaon@naver.com'),
  ('아임커머스', 'gnews8@imcommerce.kr'),
  ('알로코리아', 'seunghun.lee@allokorea.com'),
  ('알리오코리아', 'nys8634@hanmail.net'),
  ('알토디자인', 'icechang00@naver.com'),
  ('에벤에셀기업', 'ebes@ebes.co.kr'),
  ('에스랜드', 'boyasland1@hanmail.net'),
  ('에스엔티코프', 'rmswleo@hanmail.net'),
  ('에스피플', 'mj@speople.kr'),
  ('에이치앤씨', 'hnc_0001@naver.com'),
  ('엠테크윈', 'mtechwin@naver.com'),
  ('영도금속', 'leejh0908@nate.com'),
  ('오성우산', 'ktec0880@naver.com'),
  ('와이컨텐츠', 'sjkim@ycontents.co.kr'),
  ('요아럽', 'yoaluv@naver.com'),
  ('웰크리', 'mblco@naver.com'),
  ('위드컴퍼니', 'withcom5694@naver.com'),
  ('윈스타', 'winstarmat@naver.com'),
  ('윌케이', 'ysaa8504@naver.com'),
  ('유비코리아', 'ub3@ubkorea.co.kr'),
  ('유비콜아', 'ub3@ubkorea.co.kr'),
  ('유케이특판', 'kw2023@unclekim.net'),
  ('이음전산', 'tp@eeumcorp.co.kr'),
  ('제이피글로벌', 'jpglo5954@daum.net'),
  ('지이켐텍', 'siliconeman@hanmail.net'),
  ('카파클락', 'ys.lee@kappaclock.com'),
  ('커스텀플레이스', 'custom@customplace.net'),
  ('코스맥스코리아', 'doskoi@naver.com'),
  ('쿨디자인', 'cool-design@naver.com'),
  ('큐브디컴퍼니', 'gdcmaster@gmail.com'),
  ('투엘컴퍼니', 'twobro@twolc.co.kr'),
  ('파인갤러리', 'spoart2000@daum.net'),
  ('퍼니메이드', 'funnymade@daum.net'),
  ('퍼스트비', 'fb@firstb.co.kr'),
  ('포트메리온', 'hm9389@hanmail.net'),
  ('협성트레이드', 'hst2503@hanmail.net'),
  ('혜토', 'rh360@hanmail.net')
)
SELECT p.vendor_name AS 원가표_매입처명,
       p.email       AS 원가표_이메일,
       CASE WHEN a.id IS NULL THEN '별칭 없음'
            ELSE '별칭은 있으나 거래처 미연결' END AS 사유
FROM po_emails p
LEFT JOIN erp_vendor_aliases a
       ON a.alias_type = 'purchase' AND a.erp_name = p.vendor_name
WHERE a.vendor_id IS NULL
ORDER BY 사유, p.vendor_name;


-- ── B) 원가표와 다른 이메일을 가진 거래처 (기존값 보존으로 안 바뀐 곳) ──
-- 현재이메일이 맞으면 그대로 두고, 원가표 쪽이 최신이면 매입처 허브에서 수정.
WITH po_emails(vendor_name, email) AS (VALUES
  ('(주)다이아'::text, 'daiya1991@naver.com'::text),
  ('(주)소셜빈', 'kisung@socialbean.co.kr'),
  ('AtoZ', 'k398551@naver.com'),
  ('DMC미디어', 'kkw2954@dmcmedia.co.kr'),
  ('GB컴퍼니', 'gb-support@golfboom.com'),
  ('JW아이엔씨', '7013355@jwinc.shop'),
  ('JW컴퍼니', 'karismapark48@hanmail.net'),
  ('THE SG', 'thesg0_s@naver.com'),
  ('㈜다이아', 'daiya1991@naver.com'),
  ('㈜소셜빈', 'kisung@socialbean.co.kr'),
  ('㈜에벤에셀기업', 'ebes@ebes.co.kr'),
  ('골프맥스', 'golmac@naver.com'),
  ('괴산꿀벌랜드', 'golcan@hanmail.net'),
  ('구씨공방', 'jongseok1188@hanmail.net'),
  ('기프트넷', 'gift@giftnet.co.kr'),
  ('나래티앤씨', 'admin@naraetnc.com'),
  ('나비스토리', 'ahj0417@sknabi.com'),
  ('남양유업', 'clc0718@namyangi.com'),
  ('네오프라자', 'neoplaza@neoplaza.co.kr'),
  ('네이처프라임', 'sales@nprime.co.kr'),
  ('뉴샵', 'newshop2026@naver.com'),
  ('느티나무의사랑', 'huz@huz.co.kr'),
  ('다온글로비스', 'daonglovis@daum.net'),
  ('다올에프앤지', 'daolfng@gmail.com'),
  ('다올커머스', 'daol87456@hanmail.net'),
  ('다즐코리아', 'doskoi@naver.com'),
  ('대길', '9477848@naver.com'),
  ('대상크리스탈', 'leebo99@hanmail.net'),
  ('대왕크린', 'dwtissue@naver.com'),
  ('대현상회', 'dhoil1970@naver.com'),
  ('도기야', 'new@livingnara.com'),
  ('동양키친나라', 'kcnr@hanmail.net'),
  ('두일지엘', 'ub3@ubkorea.co.kr'),
  ('라인플러스', 'sales@lineplus.com'),
  ('락앤락', 'hyuckgyu.kwon@locknlock.com'),
  ('렌켄', 'moondaeho1@naver.com'),
  ('로얄오피스', 'royalinkr@hanmail.net'),
  ('롯데택배', 'yoaluv@naver.com'),
  ('루체컴퍼니', 'luce-co@naver.com'),
  ('루치펠로', 'bavscd@rucipello.com'),
  ('리버191', 'evergreenkch@hanmail.net'),
  ('리베로앤', 'liberon4992200@daum.net'),
  ('명성', 'zerodrom21@gift.co.kr'),
  ('모든컴퍼니', 'admin@moduen.com'),
  ('무아스', 'offline@mooas.com'),
  ('무한타올우정상사', 'woojungtowel@naver.com'),
  ('바르미식품', 'barmifd@naver.com'),
  ('반디상사', 'queen-made@naver.com'),
  ('베스트라인', 'bestlinee@naver.com'),
  ('벨라코리아', 'help@bellakorea.kr'),
  ('브랜즈컴퍼니', 'b2b@brandz.co.kr'),
  ('브로스앤컴퍼니', 'yjseo@brosncompany.com'),
  ('비앤디', 'bndsa001@bndkorea.com'),
  ('비오인터내셔널', 'bointl1@naver.com'),
  ('비즈모아코리아', 'bizmoakorea@naver.com'),
  ('비즈엠넷코리아', 'thinking@bizmnet.co.kr'),
  ('비타그램', 'vitagram001@naver.com'),
  ('샘빌', 'yoonki@semvill.com'),
  ('서우글로벌', 'seowoo.njy@gmail.com'),
  ('선명농수산', 'sm22@sunnuts.co.kr'),
  ('선학', 'mblco@naver.com'),
  ('성진코아', 'whyun@sungjincore.co.kr'),
  ('세정CCR', 'sejungccr@naver.com'),
  ('솔트바이오', 'sbhmudsalt@saltbio.com'),
  ('송월타올수건이야기', 'towel79@naver.com'),
  ('쉔코리아', 'schoenkorea1@schoenkorea.co.kr'),
  ('승일', 'thinking@bizmnet.co.kr'),
  ('시즈넬', 'tfsdiffuser@gmail.com'),
  ('신성트레이드', 'kyuil9191@hanmail.net'),
  ('신영인터내셔널', 'syglc@naver.com'),
  ('신영종합상사', 'sypen@naver.com'),
  ('실리만', 'pjh@sillymann.com'),
  ('씨엘피에스', 'hbk0609@hanmail.net'),
  ('아로마코에스', 'ceo01@aromacos.kr'),
  ('아이랩코퍼레이션', 'order@ilabcorp.co.kr'),
  ('아이템허브', 'itemhub-laaon@naver.com'),
  ('아임커머스', 'gnews8@imcommerce.kr'),
  ('알로코리아', 'seunghun.lee@allokorea.com'),
  ('알리오코리아', 'nys8634@hanmail.net'),
  ('알토디자인', 'icechang00@naver.com'),
  ('에벤에셀기업', 'ebes@ebes.co.kr'),
  ('에스랜드', 'boyasland1@hanmail.net'),
  ('에스엔티코프', 'rmswleo@hanmail.net'),
  ('에스피플', 'mj@speople.kr'),
  ('에이치앤씨', 'hnc_0001@naver.com'),
  ('엠테크윈', 'mtechwin@naver.com'),
  ('영도금속', 'leejh0908@nate.com'),
  ('오성우산', 'ktec0880@naver.com'),
  ('와이컨텐츠', 'sjkim@ycontents.co.kr'),
  ('요아럽', 'yoaluv@naver.com'),
  ('웰크리', 'mblco@naver.com'),
  ('위드컴퍼니', 'withcom5694@naver.com'),
  ('윈스타', 'winstarmat@naver.com'),
  ('윌케이', 'ysaa8504@naver.com'),
  ('유비코리아', 'ub3@ubkorea.co.kr'),
  ('유비콜아', 'ub3@ubkorea.co.kr'),
  ('유케이특판', 'kw2023@unclekim.net'),
  ('이음전산', 'tp@eeumcorp.co.kr'),
  ('제이피글로벌', 'jpglo5954@daum.net'),
  ('지이켐텍', 'siliconeman@hanmail.net'),
  ('카파클락', 'ys.lee@kappaclock.com'),
  ('커스텀플레이스', 'custom@customplace.net'),
  ('코스맥스코리아', 'doskoi@naver.com'),
  ('쿨디자인', 'cool-design@naver.com'),
  ('큐브디컴퍼니', 'gdcmaster@gmail.com'),
  ('투엘컴퍼니', 'twobro@twolc.co.kr'),
  ('파인갤러리', 'spoart2000@daum.net'),
  ('퍼니메이드', 'funnymade@daum.net'),
  ('퍼스트비', 'fb@firstb.co.kr'),
  ('포트메리온', 'hm9389@hanmail.net'),
  ('협성트레이드', 'hst2503@hanmail.net'),
  ('혜토', 'rh360@hanmail.net')
),
matched AS (
  SELECT v.id,
         v.name  AS 거래처명,
         v.email AS 현재이메일,
         string_agg(DISTINCT p.email, ', ') AS 원가표_이메일,
         bool_or(v.email IS NOT DISTINCT FROM p.email) AS 일치있음
  FROM po_emails p
  JOIN erp_vendor_aliases a
    ON a.alias_type = 'purchase' AND a.erp_name = p.vendor_name
  JOIN vendors v ON v.id = a.vendor_id
  GROUP BY v.id, v.name, v.email
)
SELECT 거래처명, coalesce(현재이메일, '(비어 있음)') AS 현재이메일, 원가표_이메일
FROM matched
WHERE NOT 일치있음
ORDER BY 거래처명;
